services:
  - type: web
    name: vebdream
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: vebdream-db
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: TELEGRAM_ADMIN_ID
        sync: false
      - key: CRON_SECRET
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: GEMINI_API_KEY2
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false

databases:
  - name: vebdream-db
    plan: free
    databaseName: vebdream
    user: vebdream

